include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_specify_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
    sort_constructors_first: true
    unnecessary_this: true
    use_key_in_widget_constructors: true
    prefer_single_quotes: true
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true
    combinators_ordering: true
    comment_references: true
    invalid_case_patterns: true
    one_member_abstracts: true
    only_throw_errors: true
