// Mocks generated by Mockito 5.4.6 from annotations
// in urban_breeze/test/features/workout_history/application/facades/workout_refresh_polling_facade_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:urban_breeze/core/result/app_result.dart' as _i5;
import 'package:urban_breeze/features/integration/application/use_cases/poll_sync_status_use_case.dart'
    as _i7;
import 'package:urban_breeze/features/integration/domain/entities/sync_status.dart'
    as _i8;
import 'package:urban_breeze/features/integration/domain/repositories/integration_repository.dart'
    as _i2;
import 'package:urban_breeze/features/workout_history/application/use_cases/selective_sync_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIntegrationRepository_0 extends _i1.SmartFake
    implements _i2.IntegrationRepository {
  _FakeIntegrationRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SelectiveSyncUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSelectiveSyncUseCase extends _i1.Mock
    implements _i3.SelectiveSyncUseCase {
  MockSelectiveSyncUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.AppResult<Map<String, dynamic>?>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i4.Future<_i5.AppResult<Map<String, dynamic>?>>.value(
              _i6.dummyValue<_i5.AppResult<Map<String, dynamic>?>>(
                this,
                Invocation.method(#execute, []),
              ),
            ),
          )
          as _i4.Future<_i5.AppResult<Map<String, dynamic>?>>);
}

/// A class which mocks [PollSyncStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPollSyncStatusUseCase extends _i1.Mock
    implements _i7.PollSyncStatusUseCase {
  MockPollSyncStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IntegrationRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeIntegrationRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.IntegrationRepository);

  @override
  _i4.Future<_i5.AppResult<_i8.SyncStatus>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i4.Future<_i5.AppResult<_i8.SyncStatus>>.value(
              _i6.dummyValue<_i5.AppResult<_i8.SyncStatus>>(
                this,
                Invocation.method(#execute, []),
              ),
            ),
          )
          as _i4.Future<_i5.AppResult<_i8.SyncStatus>>);
}
