// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// 프로덕션 환경용 [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptionsProd have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptionsProd have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptionsProd have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsProd have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsProd are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEhjwTigKCOko1l_r021eu025tw-MRCNQ',
    appId: '1:723259332020:android:805eb93e016c686e1a8ee1',
    messagingSenderId: '723259332020',
    projectId: 'urban-breeze',
    storageBucket: 'urban-breeze.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAgZBbrHR6iz9nM4oDW_52O8LrFa-LV6o',
    appId: '1:723259332020:ios:8591b0d2e24ada341a8ee1',
    messagingSenderId: '723259332020',
    projectId: 'urban-breeze',
    storageBucket: 'urban-breeze.firebasestorage.app',
    androidClientId:
        '723259332020-2ms0qnupo6ntk7um52d6f8ct4s0fvk3h.apps.googleusercontent.com',
    iosClientId:
        '723259332020-btu686vg8mlo6p0kb1v5f9cd498gmuue.apps.googleusercontent.com',
    iosBundleId: 'com.inoi.urbanbreeze',
  );
}
