name: Feature CI

on:
  pull_request:
    branches:
      - develop

jobs:
  feature_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Cache pub & FVM SDK & global bin
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.pub-cache/bin
            .fvm/versions
          key: ${{ runner.os }}-fvm-${{ hashFiles('.fvmrc') }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-fvm-

      - name: Add pub-cache bin to PATH
        run: echo "${HOME}/.pub-cache/bin" >> $GITHUB_PATH

      - name: Install FVM if needed
        run: |
          if ! command -v fvm > /dev/null; then
            dart pub global activate fvm
          else
            echo "fvm already installed, skipping activation"
          fi

      - name: Install Flutter SDK via FVM
        run: fvm install

      - name: Install dependencies
        run: fvm flutter pub get

      - name: Format check
        run: fvm dart format --set-exit-if-changed .

      - name: Analyze code
        run: fvm flutter analyze
