name: Feature CI

on:
  pull_request:
    branches:
      - develop

jobs:
  feature_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Determine Flutter version from .fvmrc
        uses: kuhnroyal/flutter-fvm-config-action/config@v3
        id: fvm-config

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config.outputs.FLUTTER_CHANNEL }}
          cache: true
          cache-key: ${{ runner.os }}-flutter-${{ steps.fvm-config.outputs.FLUTTER_VERSION }}-${{ hashFiles('**/pubspec.lock') }}

      - name: Create .env file from secrets
        run: |
          echo "$SECRETS_CONTEXT" | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' > .env.dev
          echo "$SECRETS_CONTEXT" | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' > .env.prod

      - name: Install dependencies
        run: flutter pub get

      - name: Format check
        run: dart format --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze
