// Mocks generated by Mockito 5.4.6 from annotations
// in urban_breeze/test/features/integration/application/use_cases/poll_sync_status_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:urban_breeze/features/integration/domain/entities/integration_auth.dart'
    as _i2;
import 'package:urban_breeze/features/integration/domain/entities/sync_status.dart'
    as _i3;
import 'package:urban_breeze/features/integration/domain/repositories/integration_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIntegrationAuth_0 extends _i1.SmartFake
    implements _i2.IntegrationAuth {
  _FakeIntegrationAuth_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncStatus_1 extends _i1.SmartFake implements _i3.SyncStatus {
  _FakeSyncStatus_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IntegrationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIntegrationRepository extends _i1.Mock
    implements _i4.IntegrationRepository {
  MockIntegrationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.IntegrationAuth> requestIntegrationLink({
    required String? terraProvider,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestIntegrationLink, [], {
              #terraProvider: terraProvider,
            }),
            returnValue: _i5.Future<_i2.IntegrationAuth>.value(
              _FakeIntegrationAuth_0(
                this,
                Invocation.method(#requestIntegrationLink, [], {
                  #terraProvider: terraProvider,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.IntegrationAuth>);

  @override
  _i5.Future<void> getIntegrationActivity() =>
      (super.noSuchMethod(
            Invocation.method(#getIntegrationActivity, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.SyncStatus> getSyncStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getSyncStatus, []),
            returnValue: _i5.Future<_i3.SyncStatus>.value(
              _FakeSyncStatus_1(this, Invocation.method(#getSyncStatus, [])),
            ),
          )
          as _i5.Future<_i3.SyncStatus>);
}
